path: /home/shaqiloheal/ros2_ws/src/  # <- where your ros2 workspace source is

nodes: # the nodes we are going to monitor
  - node:
      name: fibonacci_action_server  # <- your Action server node name
      package: fibonacci  # <- your fibonacci package
      path: /home/shaqiloheal/ros2_ws/src/fibonacci/run.launch  # <- the script to run

monitors:
  - monitor:
      id: monitor_action
      log: ./log_action.txt
      silent: False
      actions:  # <- NOT actions here because it's offline
        - name: fibonacci/_goal
          type: custom_action_interfaces.action.Fibonacci.Goal
          action: log
        - name: fibonacci/_feedback
          type: custom_action_interfaces.action.Fibonacci.Feedback
          action: log
        - name: fibonacci/_result
          type: custom_action_interfaces.action.Fibonacci.Result
          action: log
