path: /home/shaqiloheal/ros2_ws/src/  # <- where your ros2 workspace source is

nodes: # the nodes we are going to monitor
  - node:
      name: fibonacci_action_server  # <- your Action server node name
      package: fibonacci  # <- your fibonacci package
      path: /home/shaqiloheal/ros2_ws/src/fibonacci/run.launch  # <- the script to run

monitors: # the monitors we are going to generate
  - monitor:
      id: monitor_action  # <- the monitor's name
      log: ./log_action.txt  # <- output log file
      silent: False  # <- see output in the terminal
      topics:  # <- the topics you want to monitor
        - name: fibonacci/_goal
          type: custom_action_interfaces.action.Fibonacci.Goal
          action: log
        - name: fibonacci/_feedback
          type: custom_action_interfaces.action.Fibonacci.Feedback
          action: log
        - name: fibonacci/_result
          type: custom_action_interfaces.action.Fibonacci.Result
          action: log
